/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UGie7YTcu5P
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function CarDetails() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-background text-foreground">
      <main className="container max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="grid gap-8 md:grid-cols-2 items-start">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">2023 Acme Roadster</h1>
            <p className="text-muted-foreground text-lg">A thrilling sports car with exceptional performance.</p>
            <div className="grid gap-4 mt-8">
              <img
                src="/placeholder.svg"
                alt="Exterior view of the Acme Roadster showing the sleek, aerodynamic design and bold red paint color."
                width={800}
                height={450}
                className="rounded-lg object-cover"
                style={{ aspectRatio: "800/450", objectFit: "cover" }} />
              <img
                src="/placeholder.svg"
                alt="Interior view of the Acme Roadster showing the luxurious leather seats, digital instrument cluster, and premium audio system."
                width={800}
                height={450}
                className="rounded-lg object-cover"
                style={{ aspectRatio: "800/450", objectFit: "cover" }} />
            </div>
          </div>
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold">Specifications</h2>
              <ul className="mt-4 space-y-2 text-muted-foreground">
                <li>
                  <span className="font-medium">Engine:</span> 3.0L Turbo V6
                </li>
                <li>
                  <span className="font-medium">Transmission:</span> 8-Speed Automatic
                </li>
                <li>
                  <span className="font-medium">Fuel Economy:</span> 22 MPG City, 29 MPG Highway
                </li>
                <li>
                  <span className="font-medium">Safety Features:</span> Forward Collision Warning, Automatic Emergency
                  Braking, Lane Departure Warning, Blind Spot Monitoring
                </li>
                <li>
                  <span className="font-medium">Technology:</span> 12.3-Inch Digital Instrument Cluster, 10.1-Inch
                  Touchscreen Infotainment System, Wireless Apple CarPlay and Android Auto
                </li>
              </ul>
            </div>
            <div>
              <h2 className="text-2xl font-bold">Audio Description</h2>
              <p className="mt-4 text-muted-foreground">
                Listen to a detailed narration of the Acme Roadster's features and specifications.
              </p>
              <Button className="mt-4">
                <PlayIcon className="mr-2 h-5 w-5" />
                Play Audio Description
              </Button>
            </div>
            <div>
              <h2 className="text-2xl font-bold">Accessibility</h2>
              <div className="mt-4 flex items-center space-x-4">
                <Button variant="outline" className="flex items-center space-x-2">
                  <EyeIcon className="h-5 w-5" />
                  <span>High Contrast Mode</span>
                </Button>
                <Button variant="outline" className="flex items-center space-x-2">
                  <VolumeIcon className="h-5 w-5" />
                  <span>Audio Description</span>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}

function EyeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function PlayIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>)
  );
}


function VolumeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
    </svg>)
  );
}
