/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tOp2rR7Adwr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Separator } from "@/components/ui/separator"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Homepage_v2() {
  return (
    (<div className="flex flex-col min-h-dvh">
      <header
        className="flex items-center justify-between h-16 px-4 md:px-6 border-b bg-background">
        <nav className="flex items-center gap-4 md:gap-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <CarIcon className="w-6 h-6" />
            <span className="text-lg font-semibold">Renta</span>
          </Link>
          <div className="hidden md:flex items-center gap-4">
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}>
              Search
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}>
              Ratings & Reviews
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}>
              My Bookings
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:bg-primary hover:text-primary-foreground px-3 py-2 rounded-md transition-colors"
              prefetch={false}>
              Accessibility
            </Link>
            <DropdownMenu>
              <DropdownMenuTrigger
                className="flex items-center gap-1 text-muted-foreground hover:text-foreground">
                <span>Language</span>
                <ChevronDownIcon className="h-4 w-4" />
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" prefetch={false}>
                    <FlagIcon className="h-4 w-4" />
                    <span>Türkçe</span>
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" prefetch={false}>
                    <FlagIcon className="h-4 w-4" />
                    <span>English</span>
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" prefetch={false}>
                    <FlagIcon className="h-4 w-4" />
                    <span>العربية</span>
                  </Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </nav>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon" className="rounded-full">
            <img
              src="/placeholder.svg"
              width="32"
              height="32"
              className="rounded-full"
              alt="Avatar" />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section
          className="relative w-full h-[400px] md:h-[500px] lg:h-[600px] overflow-hidden">
          <Carousel>
            <CarouselContent>
              <CarouselItem>
                <div
                  className="flex flex-col md:flex-row items-center justify-between h-full px-4 md:px-6 lg:px-10">
                  <div className="space-y-4 md:space-y-6 lg:space-y-8">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">
                      Discover the Perfect Car for Your Next Adventure
                    </h1>
                    <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground">
                      Rent from our wide selection of top-quality vehicles.
                    </p>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                  <img
                    src="/placeholder.svg"
                    width="400"
                    height="300"
                    alt="Car"
                    className="max-w-[300px] md:max-w-[400px] lg:max-w-[500px] object-contain" />
                </div>
              </CarouselItem>
              <CarouselItem>
                <div
                  className="flex flex-col md:flex-row items-center justify-between h-full px-4 md:px-6 lg:px-10">
                  <div className="space-y-4 md:space-y-6 lg:space-y-8">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">Experience the Thrill of Driving</h1>
                    <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground">
                      Rent the car of your dreams and explore the open road.
                    </p>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                  <img
                    src="/placeholder.svg"
                    width="400"
                    height="300"
                    alt="Car"
                    className="max-w-[300px] md:max-w-[400px] lg:max-w-[500px] object-contain" />
                </div>
              </CarouselItem>
              <CarouselItem>
                <div
                  className="flex flex-col md:flex-row items-center justify-between h-full px-4 md:px-6 lg:px-10">
                  <div className="space-y-4 md:space-y-6 lg:space-y-8">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">Elevate Your Travel Experience</h1>
                    <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground">
                      Rent a car that fits your lifestyle and budget.
                    </p>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                  <img
                    src="/placeholder.svg"
                    width="400"
                    height="300"
                    alt="Car"
                    className="max-w-[300px] md:max-w-[400px] lg:max-w-[500px] object-contain" />
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious
              className="absolute left-4 md:left-6 lg:left-10 top-1/2 -translate-y-1/2 z-10">
              <ChevronLeftIcon className="w-6 h-6" />
            </CarouselPrevious>
            <CarouselNext
              className="absolute right-4 md:right-6 lg:right-10 top-1/2 -translate-y-1/2 z-10">
              <ChevronRightIcon className="w-6 h-6" />
            </CarouselNext>
          </Carousel>
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-10">
          <div className="max-w-3xl mx-auto space-y-6 md:space-y-8 lg:space-y-10">
            <div className="text-center">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">About Renta</h2>
              <p className="text-muted-foreground text-lg md:text-xl lg:text-2xl">
                Renta is a leading car rental company that provides top-quality vehicles for all your travel needs. With
                a wide selection of cars and exceptional customer service, we&apos;re dedicated to making your journey
                unforgettable.
              </p>
            </div>
            <Separator />
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 md:gap-6 lg:gap-8">
              <Link
                href="#"
                className="bg-muted rounded-lg overflow-hidden group transition-all hover:bg-accent hover:text-accent-foreground"
                prefetch={false}>
                <div
                  className="p-4 md:p-6 lg:p-8 flex flex-col items-center justify-center h-full">
                  <CarIcon className="w-10 h-10 mb-4" />
                  <h3 className="text-lg md:text-xl lg:text-2xl font-semibold">SUVs</h3>
                  <p className="text-muted-foreground text-sm md:text-base lg:text-lg">
                    Explore the great outdoors in style.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-lg overflow-hidden group transition-all hover:bg-accent hover:text-accent-foreground"
                prefetch={false}>
                <div
                  className="p-4 md:p-6 lg:p-8 flex flex-col items-center justify-center h-full">
                  <SirenIcon className="w-10 h-10 mb-4" />
                  <h3 className="text-lg md:text-xl lg:text-2xl font-semibold">Sedans</h3>
                  <p className="text-muted-foreground text-sm md:text-base lg:text-lg">
                    Comfortable and efficient for everyday driving.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-lg overflow-hidden group transition-all hover:bg-accent hover:text-accent-foreground"
                prefetch={false}>
                <div
                  className="p-4 md:p-6 lg:p-8 flex flex-col items-center justify-center h-full">
                  <CaravanIcon className="w-10 h-10 mb-4" />
                  <h3 className="text-lg md:text-xl lg:text-2xl font-semibold">Minivans</h3>
                  <p className="text-muted-foreground text-sm md:text-base lg:text-lg">
                    Spacious and versatile for family adventures.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-lg overflow-hidden group transition-all hover:bg-accent hover:text-accent-foreground"
                prefetch={false}>
                <div
                  className="p-4 md:p-6 lg:p-8 flex flex-col items-center justify-center h-full">
                  <CarIcon className="w-10 h-10 mb-4" />
                  <h3 className="text-lg md:text-xl lg:text-2xl font-semibold">Sports Cars</h3>
                  <p className="text-muted-foreground text-sm md:text-base lg:text-lg">
                    Experience the thrill of high-performance driving.
                  </p>
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-10 bg-muted">
          <div className="max-w-3xl mx-auto space-y-6 md:space-y-8 lg:space-y-10">
            <div className="text-center">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Special Offers</h2>
              <p className="text-muted-foreground text-lg md:text-xl lg:text-2xl">
                Check out our latest deals and discounts on car rentals.
              </p>
            </div>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
              <Card>
                <CardHeader>
                  <CardTitle>Weekend Getaway</CardTitle>
                  <CardDescription>Rent a car for the weekend and save 20%.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="text-2xl font-bold">$99/day</div>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Family Road Trip</CardTitle>
                  <CardDescription>Rent a minivan for your next family adventure and save 15%.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="text-2xl font-bold">$129/day</div>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Business Traveler</CardTitle>
                  <CardDescription>Rent a sedan for your next business trip and save 10%.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="text-2xl font-bold">$79/day</div>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-10">
          <div className="max-w-3xl mx-auto space-y-6 md:space-y-8 lg:space-y-10">
            <div className="text-center">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Latest Reviews</h2>
              <p className="text-muted-foreground text-lg md:text-xl lg:text-2xl">
                See what our customers are saying about their experiences with Renta.
              </p>
            </div>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
              <Card>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <Avatar className="border w-12 h-12">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="font-semibold">John Doe</div>
                      <div className="text-sm text-muted-foreground">San Francisco, CA</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 text-xs font-semibold mt-4">
                    <div className="flex items-center gap-" />
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function CarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>)
  );
}


function CaravanIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="4" height="4" x="2" y="9" />
      <rect width="4" height="10" x="10" y="9" />
      <path d="M18 19V9a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v8a2 2 0 0 0 2 2h2" />
      <circle cx="8" cy="19" r="2" />
      <path d="M10 19h12v-2" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}


function SirenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 18v-6a5 5 0 1 1 10 0v6" />
      <path
        d="M5 21a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z" />
      <path d="M21 12h1" />
      <path d="M18.5 4.5 18 5" />
      <path d="M2 12h1" />
      <path d="M12 2v1" />
      <path d="m4.929 4.929.707.707" />
      <path d="M12 12v6" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
