/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tOp2rR7Adwr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts



  <header className="bg-primary text-primary-foreground py-4 md:py-6">
        <div className="container px-4 md:px-6 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Avatar className="h-9 w-9">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JP</AvatarFallback>
                  <span className="sr-only">Toggle user menu</span>
                </Avatar>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>My Account</DropdownMenuItem>
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Link href="#" className="text-lg font-medium" prefetch={false}>
              Acme Rentals
            </Link>
          </div>
          <nav className="hidden md:flex gap-4 sm:gap-6">
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Home
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Vehicles
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Offers
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              About
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4"
              prefetch={false}>
              Contact
            </Link>
          </nav>
        </div>
      </header>


        **/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import carImage from '../ui/car.png'; 
export function Homepage_v2() {
  return (
    (<div className="flex flex-col min-h-dvh">
      <header
        className="flex items-center justify-between h-16 px-4 md:px-6 border-b bg-primary text-primary-foreground py-6 md:py-12">
        <nav className=" md:flex gap-4 sm:gap-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <CarIcon className="w-6 h-6 " />
            <span className="text-lg font-semibold hover:text-primary-foreground transition-colors">Renta</span>
          </Link>
          <div className="hidden md:flex items-center gap-4">
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary-foreground transition-colors"
              prefetch={false}>
              Search
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary-foreground transition-colors"
              prefetch={false}>
              Ratings & Reviews
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary-foreground transition-colors"
              prefetch={false}>
              My Bookings
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary-foreground px-3 py-2 rounded-md transition-colors"
              prefetch={false}>
              Accessibility
            </Link>
            
          </div>
        </nav>
        <div className="flex items-center gap-4">
        <DropdownMenu>
              <DropdownMenuTrigger
                className="flex items-center gap-1 text-muted-foreground hover:text-foreground hover:text-primary-foreground transition-colors">
                <span>Language</span>
                <ChevronDownIcon className="h-4 w-4" />
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" prefetch={false}>
                    <FlagIcon className="h-4 w-4" />
                    <span>Türkçe</span>
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" prefetch={false}>
                    <FlagIcon className="h-4 w-4" />
                    <span>English</span>
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link href="#" className="flex items-center gap-2" prefetch={false}>
                    <FlagIcon className="h-4 w-4" />
                    <span>العربية</span>
                  </Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Avatar className="h-9 w-9 rounded-xl">
                  <AvatarImage src="/placeholder-user.jpg" className="rounded-xl" />
                  <AvatarFallback>JP</AvatarFallback>
                  <span className="sr-only">Toggle user menu</span>
                </Avatar>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>My Account</DropdownMenuItem>
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
      </header>
      <main className="flex-1">
      <section
       className="relative top-0 md:py-16 h-[400px] px-4 md:px-6 lg:px-10 bg-contain bg-center bg-no-repeat bg-w-full"
       style={{ backgroundImage: `url(https://th.bing.com/th/id/OIP.pNTgRo7z0-em0RVjflhABQAAAA?rs=1&pid=ImgDetMain)` }}
    >
      <div className="absolute top-0 right-0 flex flex-col items-start gap-4 p-2">
        <div>
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl md:text-4xl">Find your perfect ride</h1>
          <p className="text-sm md:text-base mt-1 md:mt-2">
            Rent the car you need, when you need it. Our wide selection and easy booking process make it simple.
          </p>
          <form className="flex gap-1 mt-2">
            <input
              type="text"
              placeholder="Search by location or vehicle"
              className="flex-1 p-1 border border-gray-300 rounded"
            />
            <Button type="submit" className="whitespace-nowrap p-1">
              Search
            </Button>
          </form>
        </div>
      </div>
    </section>

       
        <section className="relative w-full h-[400px] md:h-[500px] lg:h-[500px] overflow-hidden bg-muted">
          <div className="max-w-3xl mx-auto space-y-6 md:space-y-8 lg:space-y-10">
            <div className="text-center">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Special Offers</h2>
              <p className="text-muted-foreground text-lg md:text-xl lg:text-2xl">
                Check out our latest deals and discounts on car rentals.
              </p></div>
            </div>
            <Carousel>
            <CarouselContent>
              <CarouselItem className='h-full'>
                <div
                  className="flex flex-col md:flex-row items-center justify-between h-full px-4 md:px-6 lg:px-10">
                  <div className="space-y-4 md:space-y-6 lg:space-y-8">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">
                      Discover the Perfect Car for Your Next Adventure
                    </h1>
                    <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground">
                    Rent the car of your dreams and explore the wilderness. 15% off for the summer season on choice* cars.
                    </p>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                  <img
                  src="https://th.bing.com/th/id/OIP.m9QHgUPLEGoc9Z01TrxDEwHaEi?w=259&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
                  width="400"
                  height="300"
                  alt="Car"
                  className="w-[400px] h-[300px] object-cover"
                  />

                </div>
              </CarouselItem>
              <CarouselItem>
                <div
                  className="flex flex-col md:flex-row items-center justify-between h-full px-4 md:px-6 lg:px-10">
                  <div className="space-y-4 md:space-y-6 lg:space-y-8">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">Experience the Thrill of Driving</h1>
                    <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground">
                      Rent the car of your dreams and experience the bustling nightlife. 10% off on sports cars for a week.
                    </p>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                  <img
                  src="https://th.bing.com/th/id/OIP.52cgWj3WF9wO9DhUnM7QzwHaEK?w=326&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7"
                  alt="Car"
                  className="w-[400px] h-[300px] object-cover"
                  />
                </div>
              </CarouselItem>
              <CarouselItem>
                <div
                  className="flex flex-col md:flex-row items-center justify-between h-full px-4 md:px-6 lg:px-10">
                  <div className="space-y-4 md:space-y-6 lg:space-y-8">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">Elevate Your Travel Experience</h1>
                    <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground">
                      Hop in with some friends for the long haul. 20% on travel vans when renting up to a month.
                    </p>
                    <Button className="bg-primary text-primary-foreground">Book Now</Button>
                  </div>
                  <img
                  src="https://th.bing.com/th/id/OIP.rKo5MDyNlbpf1d6CEltozQHaE8?w=236&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"
                  width="400"
                  height="300"
                  alt="Car"
                  className="w-[400px] h-[300px] object-cover"
                  />
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious
              className="absolute left-4 md:left-6 lg:left-10 top-1/2 -translate-y-1/2 z-10">
              <ChevronLeftIcon className="w-6 h-6" />
            </CarouselPrevious>
            <CarouselNext
              className="absolute right-4 md:right-6 lg:right-10 top-1/2 -translate-y-1/2 z-10">
              <ChevronRightIcon className="w-6 h-6" />
            </CarouselNext>
          </Carousel>
          
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-10">
          <div className="max-w-3xl mx-auto space-y-6 md:space-y-8 lg:space-y-10">
            <div className="space-y-6 md:space-y-8">
              <div className="text-center">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">Explore our fleet</h2>
                <p className="text-muted-foreground md:text-lg">
                  Choose from a wide range of vehicles to fit your needs.
                </p>
              </div>
              <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                <Card>
                  <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                    <img
                      src="/placeholder.svg"
                      width={200}
                      height={150}
                      alt="Sedan"
                      className="rounded-lg" />
                    <div className="text-center">
                      <h3 className="text-xl font-semibold">Sedans</h3>
                      <p className="text-muted-foreground">Comfortable and efficient.</p>
                    </div>
                    <Button variant="outline">Rent Now</Button>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                    <img
                      src="/placeholder.svg"
                      width={200}
                      height={150}
                      alt="SUV"
                      className="rounded-lg" />
                    <div className="text-center">
                      <h3 className="text-xl font-semibold">SUVs</h3>
                      <p className="text-muted-foreground">Spacious and versatile.</p>
                    </div>
                    <Button variant="outline">Rent Now</Button>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                    <img
                      src="/placeholder.svg"
                      width={200}
                      height={150}
                      alt="Luxury"
                      className="rounded-lg" />
                    <div className="text-center">
                      <h3 className="text-xl font-semibold">Luxury</h3>
                      <p className="text-muted-foreground">Indulge in style and comfort.</p>
                    </div>
                    <Button variant="outline">Rent Now</Button>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
                    <img
                      src="/placeholder.svg"
                      width={200}
                      height={150}
                      alt="Vans"
                      className="rounded-lg" />
                    <div className="text-center">
                      <h3 className="text-xl font-semibold">Vans</h3>
                      <p className="text-muted-foreground">Spacious and practical.</p>
                    </div>
                    <Button variant="outline">Rent Now</Button>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-20 px-4 md:px-6 lg:px-10">
          <div className="max-w-10xl mx-auto space-y-6 md:space-y-8 lg:space-y-10">
            <div className="space-y-6 md:space-y-8">
              <div className="text-center">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">What our customers say</h2>
                <p className="text-muted-foreground md:text-lg">Hear from real people who have rented with us.</p>
              </div>
              <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
                <Card>
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <Avatar className="border w-12 h-12">
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div className="space-y-1">
                        <div className="font-semibold">John Doe</div>
                        <div className="flex items-center gap-1 text-xs font-medium">
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                        </div>
                      </div>
                    </div>
                    <p className="mt-4 text-muted-foreground">
                    &quot;I had a great experience renting with this company. The\n process was smooth and the car was in
                      excellent\n condition.&quot;
                    </p>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <Avatar className="border w-12 h-12">
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>SM</AvatarFallback>
                      </Avatar>
                      <div className="space-y-1">
                        <div className="font-semibold">Sarah Miller</div>
                        <div className="flex items-center gap-1 text-xs font-medium">
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                        </div>
                      </div>
                    </div>
                    <p className="mt-4 text-muted-foreground">
                    &quot;I was impressed by the wide selection of vehicles and\n the competitive prices. I&apos;ll definitely
                      be renting from\n them again.&quot;
                    </p>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <Avatar className="border w-12 h-12">
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>MJ</AvatarFallback>
                      </Avatar>
                      <div className="space-y-1">
                        <div className="font-semibold">Michael Johnson</div>
                        <div className="flex items-center gap-1 text-xs font-medium">
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                          <StarIcon className="w-4 h-4 fill-primary" />
                        </div>
                      </div>
                    </div>
                    <p className="mt-4 text-muted-foreground">
                    &quot;The rental process was quick and easy, and the staff\n was very helpful. I would definitely
                      recommend this\n company to anyone looking to rent a car.&quot;
                    </p>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex items-center justify-between h-fit px-4 md:px-6 border-b bg-primary text-primary-foreground py-6 md:py-12">
          <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
        <div className="grid gap-1">
          <h3 className="font-semibold">Company</h3>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            About Us
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Our Team
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Careers
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Products</h3>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Cars
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Vans
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Accessibilty Vehicles
          </Link>
          
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Resources</h3>
          <Link href="#" prefetch={false } className=" hover:text-muted-foreground  rounded-md transition-colors">
            FAQ
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Ratings and reviews
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Support
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Legal</h3>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Privacy Policy
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Terms of Service
          </Link>
          <Link href="#" prefetch={false} className=" hover:text-muted-foreground  rounded-md transition-colors">
            Cookie Policy
          </Link>
        </div>
        
      </div><h3> &#169;2024 Renta, Rent A Car Services</h3>
        </footer>
    </div>)
  );
}

function CarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>)
  );
}


function CaravanIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="4" height="4" x="2" y="9" />
      <rect width="4" height="10" x="10" y="9" />
      <path d="M18 19V9a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v8a2 2 0 0 0 2 2h2" />
      <circle cx="8" cy="19" r="2" />
      <path d="M10 19h12v-2" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}


function SirenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 18v-6a5 5 0 1 1 10 0v6" />
      <path
        d="M5 21a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z" />
      <path d="M21 12h1" />
      <path d="M18.5 4.5 18 5" />
      <path d="M2 12h1" />
      <path d="M12 2v1" />
      <path d="m4.929 4.929.707.707" />
      <path d="M12 12v6" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}
